export default Types = {
  REQUEST_TODO_LIST: 'REQUEST_TODO_LIST',
  SUCCESS_TODO_LIST: 'SUCCESS_TODO_LIST',
  FAILURE_TODO_LIST: 'FAILURE_TODO_LIST',
  REQUEST_DETAILS_MOVIE: 'REQUEST_DETAILS_MOVIE',
  SUCCESS_DETAILS_MOVIE: 'SUCCESS_DETAILS_MOVIE',
};